const phrases1 = {
  "1": "Mas os que confiam no Senhor renovarão as suas forças. Voarão nas alturas como águias; correrão e não se fatigarão, caminharão e não se cansarão. (Isaías 40:31)",
  "2": "Confie no Senhor e faça o bem; assim você habitará na terra e desfrutará segurança. (Salmos 37:3)",
  "3": "Se podes?, disse Jesus. Tudo é possível àquele que crê. (Marcos 9:23)",
  "4": "Deus é o nosso refúgio e fortaleza, socorro bem presente nas tribulações. (Salmos 46:1)",
  "5": "O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus é o meu rochedo, em quem me refugio. Ele é o meu escudo e o poder que me salva, a minha torre alta. (Salmo 18:2)",
  "6": "O Senhor te guardará de todo o mal; guardará a tua alma. O Senhor guardará a tua entrada e a tua saída, desde agora e para sempre. (Salmos 121:7-8)",
  "7": "Nada temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço e te ajudo, e te sustento com a minha destra justa. (Isaías 41:10)",
  "8": "Em Deus, cuja palavra eu louvo, em Deus eu confio e não temerei. Que poderá fazer-me o simples mortal? (Salmos 56:4)",
  "9": "O Senhor é bom, um refúgio em tempos de angústia. Ele protege os que nele confiam. (Naum 1:7)",
  "10": "O meu socorro vem do Senhor, que fez os céus e a terra. (Salmos 121:2)",
  "11": "Pois eu bem sei os planos que estou projetando para vós, diz o Senhor; planos de paz e não de mal, para vos dar um futuro e uma esperança. (Jeremias 29:11)",
  "12": "Deem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus. (1 Tessalonicenses 5:18)",
  "13": "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento. (Provérbios 3:5)",
  "14": "O SENHOR é o meu pastor, nada me faltará. (Salmos 23:1)",
  "15": "Não se preocupem com nada, mas em todas as orações peçam a Deus o que vocês precisam e orem sempre com o coração agradecido. Filipenses 4:6",
  "16": "E tudo o que fizerem, façam de todo o coração, como para o Senhor, e não para os homens. Colossenses 3:23",
  "17": "Este é o dia que fez o SENHOR; regozijemo-nos e alegremo-nos nele. Salmos 118:24",
  "18": "O SENHOR é a minha luz e a minha salvação; de quem terei temor? O SENHOR é o meu forte refúgio; de quem terei medo? (Salmos 27:1)",
  "19": "Por isso não desanimamos. Embora exteriormente estejamos a desgastar-nos, interiormente estamos sendo renovados dia após dia. (2 coríntios 4:16)",
  "20": "Não ameis o mundo, nem o que no mundo há. Se alguém ama o mundo, o amor do Pai não está nele. (1 João 2:15)",
  "21": "O que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé. (João 5:4)",
  "22": "Não to mandei eu? Esforça-te, e tem bom ânimo; não temas, nem te espantes; porque o Senhor teu Deus é contigo, por onde quer que andares. (Josué 1:9)",
  "23": "Portanto, agora nenhuma condenação há para os que estão em Cristo Jesus, que não andam segundo a carne, mas segundo o espírito. (Romanos 8:1)",
  "24": "Portanto nós também, pois que estamos rodeados de uma tão grande nuvem de testemunhas, deixemos todo o embaraço, e o pecado que tão de perto nos rodeia, e corramos com paciência a carreira que nos está proposta, (Hebreus 12:1)",
  "25": "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará. (Salmo 91:1)",
  "26": "Combati o bom combate, acabei a carreira, guardei a fé. (Timóteo 4:7)",
  "27": "Esforçai-vos, e ele fortalecerá o vosso coração, vós todos que esperais no Senhor. (Salmos 31:24)",
  "28": "Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio. – 2 Timóteo 1:7.",
  "29": "Posso todas as coisas em Cristo que me fortalece. Filipenses 4:13",
  "30": "Se Deus é por nós, quem será contra nós? (Romanos 8:31)",
  "31": "Não te deixes vencer pelo mal, mas vence o mal com o bem. (Romanos 12:21)",
};
